### ISSUE TITLE
Big big problem in powers_of_ten.rb

### ISSUE THREAD

**Issue by JohnSmall** [markburns/numbers_in_words#21]
`POWERS_RX = Regexp.union(POWERS_OF_TEN.values[1..]).freeze`

Fails because of a syntax error.

 `[1..]` should be `[1..x]` where x is some integer. 

We can't see how you could even run your tests with this in place because ours fail with the syntax error. We've switched back to 0.4.0

**Comment by markburns** [comment]
Hi.
This is a new ruby feature and was auto added by rubocop autocorrect. The tests did pass when I dropped support for older rubies.
I'm definitely not tied to it though so happy to accept a PR to change back and add the older rubies back on CI.

**Comment by markburns** [comment]
This (correct but breaking on older rubies) change has now been reverted as per #23 and is released in 1.0.0
