### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by AxelTheGerman** [markburns/numbers_in_words#26]
Hi @markburns 

Thanks so much for creating and maintaining this gem. I recently started using it and seems to work great for what I need.

Would it be possible to maintain a changelog? I just noticed the version got bumped to 1.x :tada: congrats! Are there any breaking changes? Looking at the commit history there might be some change surrounding older ruby versions and possibly some big fixes?

Thanks again for your work,
Axel

**Comment by markburns** [comment]
Hey Axel

The move to 1.0.0 was really about drawing a line in the sand and yes I'll support a change log from here on out.

There wasn't really a breaking change on jumping to 1.x in the numbers_in_words ruby API itself but one of the 0.x releases had introduced a bug for older rubies. I've fixed this bug for those rubies now.

Some internal code was accessing an array like `arr[n..]` which is a newer ruby feature equivalent to `arr[n..-1]`. This was introduced by rubocop autocorrection. 

Anyway a strong yes for a changelog going forwards from here.
