### ISSUE TITLE
Please add CHANGELOG.md

### ISSUE THREAD

**Issue by AxelTheGerman** [markburns/numbers_in_words#27]
@markburns thank you for open sourcing this cool gem!

Do you think it would be possible to maintain a changelog? I saw the version got recently bumped to 1.0 but I couldn't find out why - this is often when incompatible changes are made (I assume support for older ruby versions might have been dropped?)

This might help https://keepachangelog.com/en/1.0.0

Thanks again and merry Christmas!

**Comment by markburns** [comment]
Hi @AxelTheGerman 

Merry Christmas 

I presume during Christmas festivities you'd forgotten your recent request for a change log.

My answer is still as per #26 let's close this and you can reply there if you like.
